### ISSUE TITLE
illegal class/method/package names or modifiers

### ISSUE THREAD

**Issue by QwertyYtPL** [Storyyeller/Krakatau#184]
Can decompiler rename illegal class names like "new" or illegal package names like "native"?? It will be helpful, I think that decompiler should decompile to legal java code without any errors...

**Comment by QwertyYtPL** [comment]
Also it should do something with static classes because these are not allowed too

**Comment by Storyyeller** [comment]
There's a lot of things you can do in Java bytecode that have no equivalent in the Java language. Krakatau does its best to map bytecode into legal Java, but when that is impossible, it strives to provide Java-like code that is at least useful for reverse engineering. 

Automatic renaming has downsides, because it can be confusing for reverse engineers if they don't realize things have been renamed, and it breaks reflection, etc.
