### ISSUE TITLE
crash with useless trycatches

### ISSUE THREAD

**Issue by Janmm14** [Storyyeller/Krakatau#199]
I've seen Krakatau crashing with exception handle entries where all 3 labels (start, end, handler) are the same. Should be fine to ignore these instead of crashing.
On my phone atm and suddenly remembered I wanted to report this, so no logs / sample.

**Comment by Storyyeller** [comment]
Thanks, I'll see if I can reproduce that later.

**Comment by Storyyeller** [comment]
I was unable to reproduce the issue. I tried creating a class with an exception handler where all three labels are the same, but the JVM rejected it, even as far back as Java 8. Since it won't run on the JVM, it's better to just print out an error message rather than trying to handle it in the decompiler, IMO.

**Comment by Janmm14** [comment]
I see, weird. Maybe the jar I had in mind was meant to run only with noverify or idk what. Anyway I'll then just continue using my transformer which removes these.
