### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by samczsun** [Storyyeller/Krakatau#56]
Hello,

My project (Helios) is ready for release but I need to work out licensing issues first. I would like to license under Apache 2.0 and nearly all of my dependencies are Apache 2.0-compatible (including Enjarify). However, Krakatau is not.

Will you consider relicensing Krakatau under the Apache 2.0 license? Alternatively, if you could grant me an exception to include Krakatau with Helios that would also work.

Regards.

**Comment by Storyyeller** [comment]
Reliscensing is tricky, because there are 2 commits from other people, so I'd either have to get their permission or remove those parts. Which isn't hard but it's something I'd have to look into.

To what extent does Helios interact with Krakatau? I'm not a lawyer, but based on my understanding of http://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem and http://www.gnu.org/licenses/gpl-faq.html#MereAggregation, it should be find if you just use the command line interface.

**Comment by samczsun** [comment]
I see. After reading the first link you provided, I think technically that should be applicable. Although I am packaging Krakatau directly, I am communicating over the OS as a process, which should make them two separate programs.

I'll give it a go because I'd really like to wrap up and release an alpha, however it's really shaky legal footing. I would still appreciate it if you could grant an exception for what code you do own and I can remove the code from other people (for a general purpose, they're required, but for my specific use they can be removed without affecting the overall program)
